name: build-image

# todo: 透传更多参数给“docker/build-push-action”
on:
  workflow_call:
    inputs:
      afterCheckOut:
        description: "在仓库代码checkout之后运行的命令"
        default: "ls ."
        required: false
        type: string
      context:
        description: "构建镜像的上下文，及文件夹路径"
        default: "."
        required: false
        type: string
      platforms:
        description: "构建镜像的平台"
        default: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x"
        required: false
        type: string
      push:
        description: "是否推送的镜像仓库"
        default: false
        required: false
        type: boolean
      tags:
        description: "构建镜像的tags"
        default: "latest"
        required: false
        type: string
      build-args:
        description: "构建镜像的运行时的参数"
        required: false
        type: string
    secrets:
      WORKFLOW_SECRET:
        required: true
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Run Command After Checkout
        run: ${{ inputs.afterCheckOut }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          context: ${{ inputs.context }}
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags }}
          build-args: ${{ inputs.build-args }}
